### ISSUE TITLE
Upgrade gem to ruby 2.6 

### ISSUE THREAD

**Issue by ck2000** [mpm/taxger#4]
I am receiving some deprecating warnings with ruby 2.6.3 e.g.:

warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

If I am running via rails console the following:

`tax = Taxger::Lohnsteuer.calculate(2015, stkl: 1, lzz: 1, re4: 70_000 * 100)`

```
Traceback (most recent call last):
        1: from (irb):5
NoMethodError (undefined method `divide' for 0.0:BigDecimal)
Did you mean?  divmod
```

Could someone please help me out with these two messages? 
Cheers

**Comment by ck2000** [comment]
I am been trying the solve the deprecated warnings by replacing `BigDecimal.new is deprecated; use BigDecimal()`. Now I am receiving another error message:

```
2.6.3 :001 > tax = Taxger::Lohnsteuer.calculate(2015, stkl: 1, lzz: 1, re4: 70_000 * 100)
"year {:stkl=>1, :lzz=>1, :re4=>7000000}"
Traceback (most recent call last):
        5: from (irb):1
        4: from lib/taxger/lohnsteuer.rb:24:in `calculate'
        3: from lib/taxger/lohnsteuer.rb:24:in `map'
        2: from lib/taxger/lohnsteuer.rb:24:in `each'
        1: from lib/taxger/lohnsteuer.rb:25:in `block in calculate'
NoMethodError (private method `BigDecimal' called for Taxger::Lohnsteuer:Module)
```
